# Generated by Django 5.2.7 on 2025-11-02 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("products", "0002_productbatch_receivinglog_shelfaudit_audititem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_audit",
            field=models.BooleanField(
                default=False, help_text="Can perform shelf audits"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_manage_staff",
            field=models.BooleanField(
                default=False, help_text="Can manage team members"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_receive_stock",
            field=models.BooleanField(
                default=False, help_text="Can perform warehouse receiving"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_analytics",
            field=models.BooleanField(
                default=False, help_text="Can access analytics dashboard"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employee_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("store_manager", "Store Manager"),
                    ("stock_receiver", "Stock Receiver"),
                    ("shelf_staff", "Shelf Staff"),
                    ("auditor", "Auditor/QA"),
                    ("head_office", "Head Office Admin"),
                ],
                default="shelf_staff",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="products.store",
            ),
        ),
    ]
