# Generated by Django 5.2.7 on 2025-11-02 14:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gtin",
                    models.CharField(
                        help_text="Global Trade Item Number (AI 01)", max_length=14
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        help_text="Batch/Lot Number (AI 10)", max_length=100
                    ),
                ),
                (
                    "gs1_barcode",
                    models.CharField(
                        blank=True,
                        help_text="Full GS1-128 barcode string",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "original_quantity",
                    models.IntegerField(
                        help_text="Initial quantity received",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("expiry_date", models.DateField(help_text="Expiry Date (AI 17)")),
                (
                    "manufacture_date",
                    models.DateField(
                        blank=True, help_text="Production Date (AI 11)", null=True
                    ),
                ),
                ("received_date", models.DateTimeField(auto_now_add=True)),
                (
                    "shipment_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "purchase_order",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("depleted", "Depleted"),
                            ("expired", "Expired"),
                            ("recalled", "Recalled"),
                            ("damaged", "Damaged"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.product",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.store",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="products.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=100, unique=True)),
                (
                    "shipment_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "purchase_order",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("received_date", models.DateTimeField(auto_now_add=True)),
                (
                    "pallet_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="receiving_photos/"
                    ),
                ),
                (
                    "invoice_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="receiving_photos/"
                    ),
                ),
                (
                    "has_expiry_issues",
                    models.BooleanField(
                        default=False,
                        help_text="True if any items are expired/near-expiry on arrival",
                    ),
                ),
                ("validation_notes", models.TextField(blank=True, null=True)),
                ("total_items", models.IntegerField(default=0)),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("partial", "Partially Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_receivings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batches",
                    models.ManyToManyField(
                        related_name="receiving_logs", to="products.productbatch"
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving_logs",
                        to="products.store",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receiving_logs",
                        to="products.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_date"],
            },
        ),
        migrations.CreateModel(
            name="ShelfAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("audit_number", models.CharField(max_length=100, unique=True)),
                ("audit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("full_store", "Full Store Audit"),
                            ("category", "Category Audit"),
                            ("location", "Location Audit"),
                            ("random", "Random Spot Check"),
                        ],
                        default="location",
                        max_length=20,
                    ),
                ),
                ("items_checked", models.IntegerField(default=0)),
                ("items_expired", models.IntegerField(default=0)),
                ("items_near_expiry", models.IntegerField(default=0)),
                ("items_damaged", models.IntegerField(default=0)),
                ("items_misplaced", models.IntegerField(default=0)),
                (
                    "audit_photos",
                    models.JSONField(
                        blank=True, help_text="Array of photo URLs", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("flagged", "Issues Flagged"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("action_required", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conducted_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audits",
                        to="products.category",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_audits",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-audit_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_found",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("quantity_expected", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("expired", "Expired"),
                            ("near_expiry", "Near Expiry"),
                            ("damaged", "Damaged"),
                            ("misplaced", "Misplaced"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="audit_photos/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_records",
                        to="products.productbatch",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_items",
                        to="products.shelfaudit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShelfLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aisle",
                    models.CharField(
                        help_text="Aisle number/name (e.g., 'A3', 'Dairy Aisle')",
                        max_length=50,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        help_text="Section within aisle (e.g., 'Top Shelf', 'Section 2')",
                        max_length=50,
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Specific position (e.g., 'Left Corner')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "location_code",
                    models.CharField(
                        help_text="Unique code like 'A3-S2-L'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True,
                        help_text="QR code for this location",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="shelf_qr_codes/"
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum units this location can hold",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("x_coordinate", models.FloatField(blank=True, null=True)),
                ("y_coordinate", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelf_locations",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "ordering": ["aisle", "section", "position"],
            },
        ),
        migrations.AddField(
            model_name="shelfaudit",
            name="shelf_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audits",
                to="products.shelflocation",
            ),
        ),
        migrations.CreateModel(
            name="ExpiryAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical (< 7 days)"),
                            ("high", "High (7-15 days)"),
                            ("medium", "Medium (15-30 days)"),
                            ("low", "Low (30+ days)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("days_until_expiry", models.IntegerField()),
                ("quantity_at_risk", models.IntegerField()),
                (
                    "estimated_loss",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Potential monetary loss",
                        max_digits=10,
                    ),
                ),
                (
                    "suggested_action",
                    models.CharField(
                        choices=[
                            ("discount", "Apply Discount"),
                            ("clearance", "Move to Clearance"),
                            ("return", "Return to Supplier"),
                            ("dispose", "Dispose"),
                            ("none", "No Action Needed"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "suggested_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suggested discount %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                (
                    "resolution_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("discount", "Apply Discount"),
                            ("clearance", "Move to Clearance"),
                            ("return", "Return to Supplier"),
                            ("dispose", "Dispose"),
                            ("none", "No Action Needed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_alerts",
                        to="products.store",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry_alerts",
                        to="products.productbatch",
                    ),
                ),
                (
                    "shelf_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="products.shelflocation",
                    ),
                ),
            ],
            options={
                "ordering": ["days_until_expiry", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Quantity at this location",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "placement_photo",
                    models.ImageField(blank=True, null=True, upload_to="shelf_photos/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="False when batch is removed from this location",
                    ),
                ),
                (
                    "placed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placed_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="products.productbatch",
                    ),
                ),
                (
                    "shelf_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="products.shelflocation",
                    ),
                ),
            ],
            options={
                "ordering": ["-placed_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("shelf_check", "Shelf Check"),
                            ("expiry_review", "Expiry Review"),
                            ("restock", "Restock Items"),
                            ("dispose", "Dispose Items"),
                            ("discount", "Apply Discount"),
                            ("receive", "Receive Shipment"),
                            ("audit", "Conduct Audit"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True, null=True)),
                (
                    "completion_photo",
                    models.ImageField(blank=True, null=True, upload_to="task_photos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="products.expiryalert",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="products.productbatch",
                    ),
                ),
                (
                    "shelf_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="products.shelflocation",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PhotoEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="evidence_photos/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "photo_type",
                    models.CharField(
                        choices=[
                            ("receiving", "Receiving/Warehouse"),
                            ("shelf_placement", "Shelf Placement"),
                            ("audit", "Audit"),
                            ("task_completion", "Task Completion"),
                            ("expiry_issue", "Expiry Issue"),
                            ("damage", "Damage Report"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="products.store",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="products.productbatch",
                    ),
                ),
                (
                    "receiving_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="products.receivinglog",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="products.shelfaudit",
                    ),
                ),
                (
                    "shelf_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="products.shelflocation",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="products.task",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Photo Evidence",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["gtin", "batch_number"], name="products_pr_gtin_826740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(
                fields=["expiry_date"], name="products_pr_expiry__54cc14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productbatch",
            index=models.Index(fields=["status"], name="products_pr_status_ee6a63_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="productbatch",
            unique_together={("gtin", "batch_number", "store")},
        ),
        migrations.AlterUniqueTogether(
            name="shelflocation",
            unique_together={("store", "aisle", "section", "position")},
        ),
        migrations.AddIndex(
            model_name="expiryalert",
            index=models.Index(
                fields=["severity", "is_resolved"],
                name="products_ex_severit_c8dcc2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expiryalert",
            index=models.Index(
                fields=["days_until_expiry"], name="products_ex_days_un_4328aa_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batchlocation",
            unique_together={("batch", "shelf_location")},
        ),
    ]
