# Generated by Django 5.2.7 on 2025-11-02 14:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_productbatch_receivinglog_shelfaudit_audititem_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2, help_text="Discount %", max_digits=5
                    ),
                ),
                (
                    "discounted_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("effective_from", models.DateTimeField()),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("near_expiry", "Near Expiry"),
                            ("expiring_soon", "Expiring Soon"),
                            ("overstock", "Overstock"),
                            ("clearance", "Clearance"),
                            ("promotional", "Promotional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("days_to_expiry", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_synced_to_pos",
                    models.BooleanField(
                        default=False, help_text="Synced to Point of Sale system"
                    ),
                ),
                ("quantity_sold", models.IntegerField(default=0)),
                (
                    "revenue_generated",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "waste_prevented",
                    models.IntegerField(
                        default=0, help_text="Units that would have expired"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_pricing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_pricing",
                        to="products.productbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pricing",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_pricing",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                (
                    "email_expiry_critical",
                    models.BooleanField(
                        default=True, help_text="Email for critical expiry (<7 days)"
                    ),
                ),
                (
                    "email_expiry_high",
                    models.BooleanField(
                        default=True, help_text="Email for high priority (7-15 days)"
                    ),
                ),
                (
                    "email_expiry_medium",
                    models.BooleanField(
                        default=False,
                        help_text="Email for medium priority (15-30 days)",
                    ),
                ),
                ("push_enabled", models.BooleanField(default=True)),
                ("push_expiry_critical", models.BooleanField(default=True)),
                ("push_expiry_high", models.BooleanField(default=True)),
                ("push_expiry_medium", models.BooleanField(default=False)),
                ("push_task_assigned", models.BooleanField(default=True)),
                ("push_task_due", models.BooleanField(default=True)),
                (
                    "daily_digest",
                    models.BooleanField(
                        default=True, help_text="Receive daily summary email"
                    ),
                ),
                (
                    "weekly_digest",
                    models.BooleanField(
                        default=True, help_text="Receive weekly report"
                    ),
                ),
                (
                    "digest_time",
                    models.TimeField(
                        default="08:00", help_text="Time to send daily digest"
                    ),
                ),
                ("fcm_token", models.CharField(blank=True, max_length=255, null=True)),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="WastageReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=100, unique=True)),
                ("report_date", models.DateTimeField(auto_now_add=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_items_wasted", models.IntegerField(default=0)),
                (
                    "total_monetary_loss",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("regulatory_report_filed", models.BooleanField(default=False)),
                (
                    "regulatory_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "corrective_actions",
                    models.TextField(
                        blank=True,
                        help_text="Actions taken to prevent future wastage",
                        null=True,
                    ),
                ),
                (
                    "report_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="wastage_reports/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_wastage_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_wastage_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_wastage_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastage_reports",
                        to="products.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="WastageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("batch_number", models.CharField(max_length=100)),
                ("expiry_date", models.DateField()),
                (
                    "quantity_wasted",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_loss", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("expired", "Expired"),
                            ("near_expiry", "Near Expiry (Unsold)"),
                            ("damaged", "Damaged"),
                            ("recalled", "Product Recall"),
                            ("quality_issue", "Quality Issue"),
                            ("overstock", "Overstock/Excess"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "disposal_method",
                    models.CharField(
                        blank=True,
                        help_text="How item was disposed",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("disposal_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="wastage_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wastage_records",
                        to="products.productbatch",
                    ),
                ),
                (
                    "disposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disposed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wastage_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.wastagereport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ComplianceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("log_number", models.CharField(max_length=100, unique=True)),
                ("log_date", models.DateTimeField(auto_now_add=True)),
                (
                    "log_type",
                    models.CharField(
                        choices=[
                            ("inspection", "Regulatory Inspection"),
                            ("internal_audit", "Internal Audit"),
                            ("fssai", "FSSAI Compliance"),
                            ("supplier_audit", "Supplier Audit"),
                            ("batch_recall", "Batch Recall"),
                            ("expiry_disposal", "Expiry Product Disposal"),
                            ("training", "Staff Training"),
                            ("incident", "Incident Report"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "regulation_reference",
                    models.CharField(
                        blank=True,
                        help_text="e.g., FSSAI License No.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "inspector_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "inspector_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("partial", "Partially Compliant"),
                            ("pending", "Pending Review"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("actions_required", models.TextField(blank=True, null=True)),
                ("action_deadline", models.DateField(blank=True, null=True)),
                ("action_completed", models.BooleanField(default=False)),
                ("action_completion_date", models.DateField(blank=True, null=True)),
                (
                    "supporting_documents",
                    models.JSONField(
                        blank=True, help_text="Array of document URLs", null=True
                    ),
                ),
                ("certificate_issued", models.BooleanField(default=False)),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="compliance_certificates/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compliance_logs",
                        to="products.productbatch",
                    ),
                ),
                (
                    "logged_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_compliance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_logs",
                        to="products.store",
                    ),
                ),
                (
                    "wastage_reports",
                    models.ManyToManyField(
                        blank=True,
                        related_name="compliance_logs",
                        to="products.wastagereport",
                    ),
                ),
            ],
            options={
                "ordering": ["-log_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_deliveries", models.IntegerField(default=0)),
                ("on_time_deliveries", models.IntegerField(default=0)),
                ("late_deliveries", models.IntegerField(default=0)),
                (
                    "avg_delay_days",
                    models.FloatField(default=0, help_text="Average delay in days"),
                ),
                ("total_items_received", models.IntegerField(default=0)),
                (
                    "items_with_expiry_issues",
                    models.IntegerField(
                        default=0, help_text="Items expired or near-expiry on arrival"
                    ),
                ),
                ("items_damaged", models.IntegerField(default=0)),
                ("items_rejected", models.IntegerField(default=0)),
                (
                    "total_value_received",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "value_of_issues",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Cost of rejected/damaged items",
                        max_digits=12,
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        default=0, help_text="0-100 based on quality metrics"
                    ),
                ),
                (
                    "delivery_score",
                    models.FloatField(
                        default=0, help_text="0-100 based on delivery metrics"
                    ),
                ),
                (
                    "overall_score",
                    models.FloatField(
                        default=0, help_text="Weighted average of all metrics"
                    ),
                ),
                (
                    "performance_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "action_plan",
                    models.TextField(
                        blank=True,
                        help_text="Improvement plan for poor performers",
                        null=True,
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "calculated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_performance_calcs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_performance",
                        to="products.store",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_records",
                        to="products.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "overall_score"],
                "unique_together": {
                    ("supplier", "store", "period_start", "period_end")
                },
            },
        ),
    ]
